apiVersion: v1
kind: Service
metadata:
  name: task-manager
spec:
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32081  # Different port for prod (32080 is for dev)
      protocol: TCP
